name: Imran Ariffin
headline: Software Engineer & Full Stack Developer
profile_img_url: https://avatars0.githubusercontent.com/u/5580715?s=400&v=4
github_repo_url: https://github.com/imranariffin/imranariffin.github.io

collections:
  - timeline
  - social
  - projects

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
