name: Amir Ariffin
headline: Software Engineer & Full Stack Developer
profile_img_url: https://avatars3.githubusercontent.com/u/22372978?v=4&s=460
github_repo_url: https://github.com/cglotr/cglotr.github.io

collections:
  - timeline
  - social
  - projects

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
